### ISSUE TITLE
2019/02/17 定例会(オンライン） 21時〜

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#107]
## 連絡事項

- [x] 議題の確認・司会、議事録の確認
- [x] 今週の実績
- [x] 来週の予定
- [x] 悩み・課題の共有
- [x] その他連絡事
- [x] 来週の平日夜のもくもく会の場所と日程の決定
- [x] Demodayに向けての話（本日野呂さんと少し話す予定なので、明日までに議題を具体化します）
 #122
- [x] タスクの再分配

## 技術検討

- [x] ログインの仕様
- [x] 掲示板機能仕様の強化レビュー

**Comment by tsu-nera** [comment]
2/16は予定がありましたので、22:00開催か、2/17開催希望です。

**Comment by takahashi19** [comment]
定例会の場所
#109 
もし提案あれば #109 にコメントお願いします。

**Comment by takahashi19** [comment]
議題提案
①来週の平日夜のもくもく会の場所と日程の決定
②Demodayに向けての話（本日野呂さんと少し話す予定なので、明日までに議題を具体化します）

**Comment by tsu-nera** [comment]
## 週報(テンプレート)

### 今週の実績

### 来週の予定

### 課題

### その他連絡事項

**Comment by tsu-nera** [comment]
## 掲示板機能仕様の強化レビューについて

### 目的

今週、掲示板機能はある程度完成させたい。そのため、仕様を強化レビューすることで、不明点や手戻りをなくし、進捗をブレストさせることが目的。

### 対象

#43 
#43 
#44

**Comment by tsu-nera** [comment]
## タスクの再分配

以下のタスクを分配したい。

- 掲示板コメント機能 - 実装
- マイページ - 設計
- 削除・募集終了 - 設計

### タスクの分配案

- 高橋さんか空くので、マイページの設計を割り当てたい。
- いぬたさんがもし参加するれば、掲示板コメント機能。
- 原田はワイルドカードで、割当がないところをやっておく。

**Comment by tsu-nera** [comment]
## 週報 (tsu-nera)

### 今週の実績

- 新メンバー探し
- 掲示板コメント機能の設計

### 来週の予定

議題にあげました。

### 課題

なし

### その他連絡事項

私のもっている別の方のプロジェクトは機能開発は終わり、リリースに向けた準備になりました。こっちのプロジェクトも見通しは立てて安定させたい。

**Comment by dh-megane** [comment]
## 週報 (dh_megane)

### 今週の実績（予実ベース）

先週の週報で記載した予定に対する実績をベースに書きます。

- 担当機能分の実装（大きく8項目あります）[詳細](https://github.com/WEBsinjyuku/github-open-products/pull/104#issue-251655689)
→　上記「詳細」で記載したタスクを着手・仕掛中。状況は下記通り（**予定通り**）
＊ 8 : 8 : 8 : 8 になれば、担当機能は完了しましたという状態です。
予定：【全体：ローカルでの作業完：PR実施中：PR完】  8 : 4 : 4 : 4 
　　　　APIを組み込む手前までは完了させる。
**実績：【全体：ローカルでの作業完：PR実施中：PR完】  8 : 5 : 5 : 5** 
　　　　予定通り、APIを組み込む手前まで完了。
　　　 　ただし、API/JSONの渡し方はこれから調査が必要。　　　　

### 来週の予定
- 実装 【全体：ローカルでの作業完：PR実施中：PR完】  8 : 7 : 7 : 7
  - 個別表示画面への遷移ができるようにする。 
  - テストデータで一覧表示画面を使用方法を確認できる。

### 課題
特になし。

### その他連絡事項
- 勉強会（平日もくもく会）
　来週はどの曜日でも大丈夫かと思います。

**Comment by takahashi19** [comment]
## 週報(takahashi19)

### 今週の実績
・GitHubのログイン。あとはアラートの設定と本番環境用の設定で終わる
### 来週の予定
・GitHubログインの完成
・Demoday次第で変わると思います。
### 課題
・Review制度のあり方
・Demoday次第のタスクの再分配
### その他連絡事項
・平日もくもく勉強会の日程と場所どうするか

**Comment by dh-megane** [comment]
参加者： @tsu-nera @takahashi19 @dh-megane 
議事録担当： @dh-megane 

## 【決定事項・次回までの課題】
- 次回のもくもく会
　火・水曜日の平日の夜に企画予定
　＊仕様強化レビューを行う。
　@LeonardoMatusaki @hiromoto-kazuya  に日程ヒアリングを行う。

- タスク再分配
「掲示板コメント」「マイページ」「削除機能・募集終了」について
設計は @tsu-nera が担当してレビュー依頼を行うのでチェックすること
それぞれの実装は皆んなで分担して遂行する

- EsLint導入
　Vueの導入に伴い、EsLintも導入する（担当： @tsu-nera ）

## 【議事内容】
### 【悩み・課題】
- 現在PRのレビューを行う人（レビュア）が固定化している。
　原因は時間が割けない以外に「知識不足で指摘できない」
　「経験者に対して指摘できない」ということがあると思う。
　
　→ 知識不足は仕方がないので、
　 たとえ「分からない・指摘できない」状態でも「👍」などで反応してほしい
　 レビュー結果が「👍」だけでも良い。

### 【開発など】
- デモデイについて
　３月１日にアプリ見せる必要があるが、予選まで作業・改修は可能。
　優勝を狙うなら、UI（ユーザインタフェース）とプレゼンを強化する必要あり。
　→　デザイナ欲しい（ @takahashi19 の知り合いのデザイナは本格的な期待できない。
          レビュー程度。）他のサービスと差別化できる機能も検討が必要かも。

- 進捗が心配（３月１日に間に合うか）
　来週日曜日（２４日）までにある程度の機能を完成しないとキツい...
　３月１日に間に合わせるため、 @tsu-nera が技術支援（テコ入れ）を行う。
　→ 「掲示板コメント」「マイページ」「削除機能・募集終了」の設計をする。

　0.9版を３月１日必達に変更する案も考えたが、予選があること・@tsu-nera が
　3/10以降は仕事の兼合いで参加率が不安なため、前回確認した1.0版を3月1日必達（変更なし）

- 仕様強化レビュー
　仕様未確定部分の決定や、実装の優先順位などを臨機応変に対応したいため
　仕様強化レビューを行う。

　◾️ ログイン仕様
　GitHubトークン取得/deviseのアラート表示に苦戦。
　→　トークンが必要な箇所はコラボレータだけなので3/1以降の後回しで良い。

　◾️ プロジェクト一覧画面
　現時点では機能落とし・苦戦事項もないため、問題なさそう。
　引き続き、Rails → Vue の連携を実装して欲しい。
　Masterへのマージは来週23日になる見込。

###  【連絡事項】
- 缶詰作業（＝終日作業日）を設けたい。
　集まれる人全員で集中して作業した方が仕様決め・開発効率が高いはず。
　3月1日までに3回程度企画できればと思う。
　会場は「AWS Loft」「貸会議室」「タリーズ」などを検討。追って連絡。

- 次回のもくもく会
　仕様強化レビューを早めに企画したいこともあり、火・水曜日の平日の夜に企画予定。

- サービス利用者の確認
　想定する利用者や、技術スキルなどの前提スキルがメンバによって差異がある。
　その差異によって仕様細部の検討でズレが発生している。
　@takahashi19 のイメージをスライドに起こし、皆んなで認識合わせ・レビューする。
　仕様の認識ズレは、デモデイで優勝が見込める・どちらのほうがより利用者が多いか
　という点を基準に判断したい。
