### ISSUE TITLE
定例会の場所と曜日検討

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#109]
場所候補
・新宿または新宿三丁目＞渋谷
曜日
①平日もくもく会水曜日19時〜21時
②休日もくもく会＋ミーティング：土曜日または日曜日、16時〜22時くらいまで
（③）木曜日13時〜18時：AWSロフト勉強会（目黒）
条件
・Wi-fi
・電源

**Comment by takahashi19** [comment]
## 新宿エリア
1. [勉強カフェ(新宿)](https://www.benkyo-cafe.net/studio/shinjuku/)
　・料金：1時間１千円
　・営業時間：平日：7:00-23:00、土曜日：10:00-22:00
　・場所：新宿駅、南新宿駅（新宿駅西側）
　・その他：コーヒー等は飲み放題
1. 

## 渋谷エリア
1. [Connecting The Dots](https://dots.bz/shibuya)
　・料金：1350円（1日）
　・営業時間：10時〜19時
　・その他：飲み物は持参

**Comment by tsu-nera** [comment]
connecting the dot's は、昨日いったらそこそこ混んでいました。６Fに６人かけのテーブルが３つあるのですが、午後はすべて埋まりました。もしConnecting the dot'sならば、誰かが午前中のうちに乗り込んで席をとり、13:00からがいいと思います。

**Comment by takahashi19** [comment]
> connecting the dot's �は、昨日いったらそこそこ混んでいました。６Fに６人かけのテーブルが３つあるのですが、午後はすべて埋まりました。もしConnecting the dot'sならば、誰かが午前中のうちに乗り込んで席をとり、13:00からがいいと思います。

情報ありがとうございます。多分僕はいく場合は1日使いたいので早めにいくと思います。connecting the dot'sの場合は13時〜19時かもう少し早い時間にしましょう。

**Comment by LeonardoMatusaki** [comment]
17日（日）15:00 ~ 24:00

**Comment by dh-megane** [comment]
dh_meganeの予定
・土曜日、日曜日ともにオッケーです。
（時間も制約なし）

**Comment by hiromoto-kazuya** [comment]
対応可能時間
2/16(土) 11-17時
2/17(日) ×
すみません、、17日は終日予定ありです。。

**Comment by tsu-nera** [comment]
16日 13:00 - 18:00
17日 18;00 -

**Comment by takahashi19** [comment]
では今週は日曜日の21時〜オンラインでやりましょう。

来週以降はまた考えます。

**Comment by hiromoto-kazuya** [comment]
@takahashi19 申し訳ないんですが昨日提示した通り日曜日は参加できないので、ログなど残っていたら後追いしますねー！

**Comment by takahashi19** [comment]
> @takahashi19 申し訳ないんですが昨日提示した通り日曜日は参加できないので、ログなど残っていたら後追いしますねー！

大丈夫ですよ！今週はいきなりだったので仕方ないです。議事録には残しますのでまた次回御願いします

**Comment by takahashi19** [comment]
3月1日用を立てたので閉じます

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/ee64dfd474ae30a827870d0725d8b668/raw)](https://gyazo.com/ee64dfd474ae30a827870d0725d8b668)
