### ISSUE TITLE
記事個別ページの掲示板機能(connpassみたいな)

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#118]
## 機能仕様

基本的には、connpassの機能をコピーします。以下詳細。

* 入力フォームと投稿ボタンを設置する。その下に投稿リストを設置する。
* フォームにメッセージを入力して、submitを押すと、投稿リストの先頭に追加される。
* 投稿リストのひとつひとつのデザインはconnpassを真似る。
* GitHubアイコンの取得表示の方法はあとで検討
* Twitter同時投稿は実装しない。
* Message Modelを作成する。カラムは id, content, create_at, updated_at, post_id
* 削除、編集はさせない。投稿のみ。

[![Screenshot from Gyazo](https://gyazo.com/c7d0ae726f1cc3d290afd07243edc291/raw)](https://gyazo.com/c7d0ae726f1cc3d290afd07243edc291)

こちらも確認お願いします。
https://github.com/WEBsinjyuku/github-open-products/issues/118#issuecomment-463829145

**Comment by tsu-nera** [comment]
connpassを模倣する。デザインはパクリ。

[![Screenshot from Gyazo](https://gyazo.com/c7d0ae726f1cc3d290afd07243edc291/raw)](https://gyazo.com/c7d0ae726f1cc3d290afd07243edc291)

**Comment by tsu-nera** [comment]
わたしもvue.jsでいいでしょうか？

**Comment by tsu-nera** [comment]
アイデアですが、API叩いて、GitHub Issueを新規作成し、そこに追記していくのはどう思いますか？？

**Comment by dh-megane** [comment]
@tsu-nera 
内容を確認しました。

気になったことを記載しますね。
### ①Message Model
　Postとの紐付けを管理するのにpost_idが必要なのではと思いました。
　（どの投稿で登録されたメッセージなのかが今のカラムだけだと分からないのでは？）
　これについて、ご意見頂けますか？

### ②Vue.js
　先日のオフライン打合せの際はSlimで書こうかなとお話されていたと
　思いますが、方針が切り替わった感じですか？
　部分的にVueやReactを採用する話を聞いたことあるので問題ないと
　思います。

### ③GitHub APIでのIssue作成
　Issueに追記するということは、コメントの情報取得元はGitHub側になる
　(＝Message Modelが不要)ということですよね？
　実際の運用を考えると、下記の点を確認する必要があるかなと思いました。

　1. プロジェクト削除、募集終了後もGitHub上では閲覧可能である？
　   アプリ側では個別表示画面への遷移は不可(閲覧できないはず)になると思うので
　   その点が気になります。

　2. GitHub上で追記したコメントも表示される？
　   そのIssue（QA)のコメントなので、GitHub上で追加したコメントも表示されて
　   良いとは思いますが、サービス側で入力・登録していないコメントが表示される
　   のは少し疑問がありました。

**Comment by tsu-nera** [comment]
レビューありがとうございます。

> 　Postとの紐付けを管理するのにpost_idが必要なのではと思いました。

post_idは必要ですが書いていませんでしたので、書きました。

> 方針が切り替わった感じですか？

はい

> 1. プロジェクト削除、募集終了後もGitHub上では閲覧可能である？

はい

> 2. GitHub上で追記したコメントも表示される？

はい。データベースに情報は持たず、GitHub APIから取得した情報を表示します。


issue表示は、やりたいが、難易度がすこし高いので、まずはやらないことにして、GitHubログインによるアカウント連携機能ができたら、作り直すことにします。

**Comment by takahashi19** [comment]
内容確認しました。仕様は問題ないと思います。ただ２点気になったのでお伝えいたします。

1. issueを連動させる動きは技術的なアピールとしては良いと思いますが、GitHubのissue自体、そもそもなれてるユーザー（リードエンジニア側）は良いと思いますが駆け出し側はGitHubすらままならないレベルも想定しているのでそのやりとり自体を意外な使い方と感じる可能性があるかと。どちらもユーザーとして対象にみてるのでそこは実装するならばその前に、勉強会などで何人かインタビューをとりたいですね。

1. この仕様については担当者が変更した場合は引き継がれますか。それともその際に、再設計する予定（変更）でしょうか。（vue.jsは@tsu-neraさんと@dh-meganeさんしか書けないので少し気になりした）

宜しく御願いします

**Comment by tsu-nera** [comment]
@takahashi19 さん、コメントありがとうございます。

1. 

GitHubをつかえないユーザは想定していませんでした・・・。そこまでリテラシが低いと、リードエンジニアにとってのメリットがなさすぎます。インタビューも募集をかける側にも必要かと思います。いづれにしろ、機能改善として、この件は後回しにします。

2. 

引き継ぎます。引き継いだひとは、vue.jsをメンテナンスすることになると思います。それは、以前平田さんと保守性について議論した結果そういう結論になっています。

**Comment by tsu-nera** [comment]
LGTMありがとうございました、いむたさんのJoinの可能性があるため、私の作業はここで止めます。

**Comment by takahashi19** [comment]
> GitHubをつかえないユーザは想定していませんでした・・・。そこまでリテラシが低いと、リードエンジニアにとってのメリットがなさすぎます。インタビューも募集をかける側にも必要かと思います。いづれにしろ、機能改善として、この件は後回しにします。

僕の趣旨としてはGitHub自体をというよりGitHubのissuesですね。特にスクールではissueの使い方を習わないので。GitHubに関してもbranch切ったりする事にどれだけなれてるかというのは個人開発だとなんとも言えないところだと思います。 僕の想定はスクールまたはProgateと修了レベルならユーザーとしてみなしています。（ここの募集要項のレベルのユーザーです。）
join前にissueまで含める場合は想定ユーザーは未経験でもDICやテックエキスパートなどの少し上位のスクールを卒業してるレベルになるかと思いますね。

**Comment by tsu-nera** [comment]
設計済。実装の担当者はバランスを見て再配置します。

**Comment by tsu-nera** [comment]
記事の新規作成機能がまだないので、Herokuの動作確認はあとでやります。閉じまーす。
