### ISSUE TITLE
Gemfileのベースをつくる

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#15]
（仮）
・ridgepole（マイグレーション）
・

**Comment by tsu-nera** [comment]
参考までに、おすすめgem
https://github.com/tsu-nera/auto-matching/blob/master/auto-matching-api-rails/Gemfile

- baby_squeel 
SQLをかきやすくするやつ

- enumerize
enumの拡張

- meta-tags
- better_errors
Chromeのデバッグをらくにする

- active_type
ActiveRecordを保守しやすくする

- ridgepole
マイグレーションが便利になる

- seed-fu
Seedが便利になる

- rubocop
- ruboco-rails_config
静的解析で必須

- annotate
rails routsすると、モデルに説明を書いてくれる

- rails_db
DBにアクセスするUIを提供

- solargraph
タグジャンプするためのツール

**Comment by tsu-nera** [comment]
なにかおすすめgemあれば推薦をお願いします。

**Comment by takahashi19** [comment]
* kaminari
　定番ですがページネーションつけるためのgem
* hirb,hirb-unicode
　Rails consoleの時に中に入ってるデータをテーブル形成で表示するツール
　https://ruby-rails.hatenadiary.com/entry/20141024/1414160189

**Comment by tsu-nera** [comment]
宙ぶらりんのイシューになっているので、いったん閉じる。
必要に応じて、導入していく。

方針としては、便利なものは取り入れるが、技術的背伸びにもなるので、相談して決める。

**Comment by tsu-nera** [comment]
ちょっとだけ #94 にまぜますね。
