### ISSUE TITLE
外部仕様設計

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#18]
外部仕様について検討するissueです。

**Comment by tsu-nera** [comment]
## tsu-nera案

### ユーザ認証機能

- GitHubアカウント連携
- サインアップ機能
- サインイン機能

### プロジェクト掲示板機能

- 新規投稿機能
- 編集機能
- 削除機能
- 一覧表示機能
- 個別表示機能

### ユーザ管理機能

- プロフィール表示機能
- ユーザ一覧機能

### メッセージ機能

ここの機能はどう実現するかは検討必要。最悪、第一リリースからは外してもよい。

- チャット
- 掲示板
- サイト内メール

### プロジェクト検索機能

これも、第一リリースからは外してもよい。プロジェクト数が少ないので。

- タグ検索
- キーワード検索

**Comment by tsu-nera** [comment]
## もともとGitHub Issueにあったもの

- ユーザアイコン投稿機能
- GitHubAPIとの連携機能
- ユーザ間チャット機能 or 個別ページの掲示板機能
- いいね機能
- プロジェクト作成機能
- ログイン機能
- 検索機能

### コメント

- ユーザアイコンはGitHubのものをとってきたい
- いいね機能は追加開発がよい気がします
- GitHubがサインアップ、サインインという用語を使っているので、そっちにあわせたほうがいいですね。

**Comment by shikky0331** [comment]
現段階では特に追加したい機能はありません。
やりたいことは「ユーザー認証機能、メッセージ機能、検索機能」に挑戦してみたいです。

**Comment by tsu-nera** [comment]
似たようなサービスを触ってみると、いろいろインスパイヤされるかもしれません。わたしは、結構アイデアはありますが、追加するよりかは、どちらかというと工数もあるため削るほうをいろいろ考えていますね。
https://github.com/WEBsinjyuku/github-open-products/issues/29

**Comment by shikky0331** [comment]
わかりました！送って頂いたサービスを実際に触ってみたいと思います！
ありがとうございます。

**Comment by LeonardoMatusaki** [comment]
現段階で追加したい機能はないです。
難易度が低い機能から、チャレンジしていきたいです！

**Comment by dh-megane** [comment]
お疲れ様です。自分も現時点で追加したい機能はないです。
Googleが活動しているOSS一覧を表示するサイト（プロジェクト掲示板機能、個別表示）がありました（英語）。
自分は、プロジェクト掲示板機能にチャレンジしてみたいです。

https://opensource.google.com/

**Comment by takaaa220** [comment]
機能に関しては僕も現状はそこまで追加したいことはありません．
個人的にこのプロジェクトで使うスタイルガイドを作成したいなぁと考えています．

**Comment by tsu-nera** [comment]
wikiに移動する。
