### ISSUE TITLE
内部仕様設計

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#19]
内部仕様について検討するissueです。

## 検討課題

- フロントエンドはなにを採用するか？集まった人で話して決める。
- 静的解析ツールの導入. rubocop & Siderで固めたい
- テスト方針。テストは書くか？なんのフレームワークをつかうか？

**Comment by tsu-nera** [comment]
## 技術選定

### バックエンド

- Ruby 2.6
- Rails 5.2.2

### フロントエンド

未定。Railsでやるならば、Slim

### DB

- PostgreSQL（予定）

### インフラ

- Heroku（予定）

### 開発環境

- Slack
- GitHub
- Google Apps

### 連携サービス

- CirCleCI
- Sider

**Comment by tsu-nera** [comment]
gemの検討

https://github.com/WEBsinjyuku/github-open-products/issues/15

**Comment by takaaa220** [comment]
rubocopはある程度採用したいです．
解析項目に関しては検討が必要ですが

**Comment by tsu-nera** [comment]
> フロントエンドはなにを採用するか？集まった人で話して決める。
VueとSlimの両方を。

> 静的解析ツールの導入. rubocop & Siderで固めたい
rubocopとEslint

> テスト方針。テストは書くか？なんのフレームワークをつかうか？
バックエンドは rspec
フロントエンドは なし
