### ISSUE TITLE
開発計画検討

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#20]
開発計画書的なものが欲しい。↓のような感じ。
https://www.innopm.com/blog/2017/05/08/108679/

関連issues  #12 #3 #4 

https://docs.google.com/presentation/d/1r-r_-ApesdjKMwJloBHpHBNFlmiykPZw098iRyYRV08/edit?usp=sharing

https://bosyu.me/users/TH03045840/wants/9679

**Comment by tsu-nera** [comment]
## プロジェクトの概要）

### 目的

GitHubで開発したい人と開発に協力したい人をマッチングすることを目的とするWebサービスを開発します。

開発を通じて、GitHubをつかったチーム開発の経験をつみます。

また、就活のための成果物をつくります。

### ゴール

QCDの優先順位をあらかじめ決めておく必要あり。品質よりもスピード重視か？

## スコープ

基本、ユーザに価値を提供することすべて。

## コスト

なし。

## スケジュール

#12 参照

## プロジェクト体制

#3 参照

## 品質マネジメント

テスト戦略をたてる必要あり。

## コミュニケーション

- GitHubとSlackを用いたコミュニケーション
- 週1,2回のミーティング

## リスクと対策

- 2中までに終わらなかった場合は？
- 途中で参加が困難なひとが出た場合は？
- マネタイズによってお金を儲けてしまった場合は？

**Comment by takahashi19** [comment]
https://github.com/moekaIII/osusowake

これ他のスクールの方のgithubですがReadmeの書き方はこんな感じですか？

**Comment by tsu-nera** [comment]
@takahashi19 
開発計画は、READMEではなくてwikiに書くことを想定しています。
READMEは READMEのベストプラクティスがありますので、それに従うのがよいです。

https://deeeet.com/writing/2014/07/31/readme/

**Comment by takahashi19** [comment]
2中までに終わらなかった場合は？
→現時点では機能を縮小し公開する事を考えています。２月末までは必須期限としたいです。

途中で参加が困難なひとが出た場合は？
→引継ぎをしてチームからは完全に抜けてもらう事が良いかと思います。権利関係的には遡及的に最初からいなかったという扱いで良いかと

マネタイズによってお金を儲けてしまった場合は？
→①アフィリエトを張った時点でOSSをプロト版（公開用）とし実運用版はプライベートにしなくてはいけない可能性があります。この点は話あいが必要かと
　②収益性についても結局全員の目的は「ポートフォリオを作る」という非営利性で集めているメンバーなのでその点は考慮してこちらでも考えて見ます

**Comment by tsu-nera** [comment]
目的は果たした。close
