### ISSUE TITLE
css設計

### ISSUE THREAD

**Issue by takaaa220** [WEBsinjyuku/github-open-products#27]
css設計はある程度ちゃんとしておきたいです。(カオスになりがちなところなので)

個人的にはBEMを使っているので、BEMを希望します。

https://qiita.com/nezurika/items/a964e21d3596b0ee4c9a

**Comment by takahashi19** [comment]
CSS設計やった事なかったですが、面白そうですね。BEMは使った事ないので勉強が必要かなと。他の方はどうですか？

**Comment by takaaa220** [comment]
最初は冗長だなぁと思いますが，慣れると圧倒的にsassが綺麗にかけますよ！

**Comment by tsu-nera** [comment]
BEMは賛成です。これって、ルールにしたがっているかチェックするLintツールはないでしょうかね？

あと、とくにデザインに強い人がいなければ、なんらかの CSS Frameworkを採用して、極力cssはかかないようにしたいです。

**Comment by takaaa220** [comment]
うーん，そのチェックするツールは聞いたことがないですね

できれば，自分は生のscssで書いていきたいです．
導入したとしてもbulmaなどのそこまで大きくないものを希望しますね．
(Bootstrapは個人的に嫌いです笑)

**Comment by takaaa220** [comment]
https://github.com/postcss/postcss-bem-linter
これとかがそうですかね
使ったことないんで調べる必要がありますが

**Comment by takaaa220** [comment]
使わない
フレームワークはbulma
