### ISSUE TITLE
githubをどのように活用するか

### ISSUE THREAD

**Issue by takaaa220** [WEBsinjyuku/github-open-products#28]
レビュー
ブランチ名
issueのアサインなど
project機能を使うか

などなど

**Comment by takahashi19** [comment]
前のチーム開発でGitHubを使用した際は
https://github.com/takahashi19/movie
こんな感じでやりました。

①コードレビュー担当を設ける方向で。コードの統一性とリチェックが必要と思います。特にrootとURL。レビューは外部でメンタ契約してる方法もありますしチームから1人その役割を出す方法もあるかと
 
②ブランチ名詳しくないので命名規則あるならあった方が勉強になるので良いです。調べて再提案します。

③issueのアサインはやります。基本的には話を取りまとめた後僕の方でやろうかと考えています

④プロジェクト機能使ってないので今回はプロジェクト機能にもチャレンジしたいです。

**Comment by takaaa220** [comment]
1. レビューに関しては，最初はある適度できる方がやって終盤に差し掛かるに当たって，全員が行うという形が私は良いと思います．（もちろん最初から全員で行っても良いのですが，gitに慣れていない方もいると思いまして）
この様に考えるのは，私自身が最近レビューをする様になり，かなり勉強になっているためです．

2. http://www.atmarkit.co.jp/ait/articles/1708/01/news015.html
ここまで詳細に分ける必要は今回はないと思いますが，参考までに．

3. 了解です．

4. ぜひやりましょう！

**Comment by tsu-nera** [comment]
1. 
masterへのマージですが、レビュー、静的解析、CircleCIによるテストの３つの関門をすべて突破しないとmargeできないようにしたいです。これは、誤操作や見逃しでmatserが壊れることを防ぐためにも重要です。GitHubのadmin権限でしか、設定できないので、今度高橋さんにおしえます。

[\[GitHub\] ブランチの保護設定を活用しよう 【レビューが通るまでマージさせんぞ】 ｜ DevelopersIO](https://dev.classmethod.jp/tool/github/protect-branch/)

2. 
運用ルールは、GitHub Flowを適用したいと考えています。いかがですか？Git Flowは複雑すぎます。先週くらいに、SNSで知り合った服バカさんがQiitaにわかりやすい解説記事を投稿していまして、これが参考になります。

[未経験がWeb系転職成功したいならgithubでissue管理して開発しよう \- Qiita](https://qiita.com/fukubaka0825/items/c7710b4e87d478c8ba3b)

わたしのプロジェクトの規約も紹介します。
https://github.com/tsu-nera/auto-matching/blob/master/.github/CONTRIBUTING.md

3. 
IssueとPRのテンプレートを設定したいです。これはGitHubの機能でadmin権限のみ操作できますので高橋さんお願いできますか？

https://github.com/tsu-nera/auto-matching/tree/master/.github

4. 
ラベルを充実させたいです。とくにLGTMはとくに重要です。知らない人はぐぐりましょう。

https://github.com/tsu-nera/auto-matching/labels

**Comment by takaaa220** [comment]
3. に関しては

**Comment by takaaa220** [comment]
https://github.com/WEBsinjyuku/github-open-products/blob/master/CONTRIBUTING.md
