### ISSUE TITLE
既存サービス調査

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#29]
似たようなサービスがあれば、機能やデザインを開発の参考にしたいので探してみる。

**Comment by tsu-nera** [comment]
[TEAMKIT](https://teamkit.jp/)

実績と繋がりで信頼を可視化し、プロジェクトのメンバー募集や参加を促進するサービス。それがTEAMKITです。

**Comment by tsu-nera** [comment]
[チームランサー \- フリーランス/パラレルワーカーのチーム支援プラットホーム](https://teamlancer.jp/)

Teamlancer は、フリーランサーやパラレルワーカーのための 
チーム支援プラットホームです。

**Comment by tsu-nera** [comment]
[InstantTeam\[インスタントチーム\]](https://www.instant.team/)

面白い アイデア
手伝ってくれる メンバー
サポーターからの お金

を集めて、アイデアを形にしていこう

**Comment by dh-megane** [comment]
https://opensource.google.com/
Googleが取り組んでいるOSS一覧の掲示板機能と、個別表示機能

**Comment by tsu-nera** [comment]
いったん調べきった感じなので、closeする。設計のときに参照したい。
