### ISSUE TITLE
開発チームの構築/役割分担どうするか

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#3]

**Comment by tsu-nera** [comment]
有言実行で仕事がはやい！

**Comment by takahashi19** [comment]
チーム発足（役割分担終了まで）は基本的には1月16日。最悪でも1月20日（日）まで。
募集方法はTwitterと参加した勉強会でのLT
それ以降も随時勉強会でLTをして募集していくが、最悪2人～3人でもスタートする。

**Comment by tsu-nera** [comment]
大体決まったのでとじる。
