### ISSUE TITLE
打ち合わせの場所と時間

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#30]
候補①
　・日曜日（または土曜日）
　・場所：渋谷
　・15時〜18時
　・貸し会議室（3時間：3150円→5人で使用の場合一人当たり504円）
候補②
　・平日
　・場所：渋谷
　・19時〜21時
　・貸し会議室（2時間：1680円→5人で使用の場合一人当たり336円）

**Comment by takaaa220** [comment]
オンラインっていう選択肢はない感じですかね？

**Comment by tsu-nera** [comment]
調整屋さんをつかって、そのつど調整する。

できれば、日曜夜は進捗確認で固定したい。
