### ISSUE TITLE
第一工期までの設計に必要なもの

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#32]
#12 
・機能の役割分担
・DBテーブル設計（簡単なもので良い）
・基礎的な機能と洗い出し
・フロントエンドの設計（CSS設計/viewの技術選定）
・開発の打ち合わせ方針（1月26日までの）

これ以外で決めるべき事があればコメントお願い致します。

**Comment by tsu-nera** [comment]
以下はissueでは、情報が埋もれるので、wikiに書いていきたい。

## タスク管理

- プロジェクト管理ツール(GitHub Project?)
- 設計をissueに切り出す作業
- 機能・タスクの優先度
- 機能タスクの工数見積

## 教育

- GitHub Flow ハンズオン(GItHub Flow未経験者)
- Dockerハンズオン(Docker未経験者)

## 設計

- README.md
- 外部設計と機能分割
- 機能設計（機能分割まででは開発できないかと）
- DB設計(機能設計ができてないと進められない)

## インフラ・CI/CD

- CircleCI
- Sider
- GitHub Branch Protection
- GitHub Label Settiings
- Heroku
- Docker
- 開発エディタ、ツール
- ローカル開発環境立ち上げ
- rails new とそのフォルダ構成
- rubocop/eslint周りの設定                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

## プロジェクトルール

- rubyのsytle(rubocop)
- javascriptのstyle(eslint)
- cssのstyle(???)
- レビュー手順(誰がどう依頼するか？）
- issue, PRのテンプレート周り

**Comment by tsu-nera** [comment]
これは済み
