### ISSUE TITLE
ユーザ認証

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#45]
#71 小issueとして追加。

**Comment by takahashi19** [comment]
##機能仕様
自動モード、手動モードの２つを用意する。
手動モードでは、複数の掲示板にボタンひとつで一括投稿する。投稿の成功・失敗がわかるようにする。
自動モードでは、投稿時刻のスケジュール設定、定期実行設定を可能にする。
掲示板に投稿する記事内容は、予め登録しておいたテンプレートからランダムに選択して投稿する。
また、指定したテンプレートを指定したサイトに投稿する機能も提供する。
投稿テンプレート作成機能を提供する。

**Comment by tsu-nera** [comment]
GitHub連携とは無関係に開発するので、タイトルを変更しました。

**Comment by takahashi19** [comment]
それぞれ別でissueあるためclose
