### ISSUE TITLE
【コメント機能】掲示板形式の投稿機能

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#46]

**Comment by takaaa220** [comment]
二種類のめっせーじきのうを

**Comment by takaaa220** [comment]
二種類のメッセージ機能を作成する

## 2chのようなコメント機能
### 概要
- プロジェクト詳細ページでコメントを投稿できる
- 返信機能として，コメント番号階層を積み上げるようなものにはしない（実装だるいので）

### 画面イメージ
https://codepen.io/taketakepro/pen/dwxXPa

### DB
Comment

| カラム名 | 型 | null | default | 外部制約 |
| :---: | :---: | :---: | :---: | :---: |
| id | integer | false | nil | false |
| content | string or text | false | nil | false |
| user_id | integer | false | nil | true |

※ 基本的にログインしているユーザのみ（処理が楽なので）

## マッチング後の参加者と主催者のDM機能
### 概要
- マッチングした人たちのみのClosedなDM
- 双方向通信を行う
- もうLineやTwitterのDMを想像してもらえれば

### DB
要検討

### 画面イメージ
TODO

**Comment by takaaa220** [comment]
## やること
- [ ] テーブル作成し，アプリケーション側でもvalidationかける(presenceのみで十分)
- [ ] create アクションを作成 (編集機能，削除機能なんて甘え，いらん)
- [ ] プロジェクト詳細画面にて，コメント表示，（2chの返信みたいにできたら十分かな）
- [ ] コメントにページネーションを追加 (優先度低め-> そんなコメント来ない，まあ20件ぐらいでいっか)
- [ ] コメント作成用フォームの作成
 (プロジェクト詳細画面に置くので十分，ログインしてない場合は表示させずログインへの導線確保)
- [ ] できれば非同期でやりたいよねぇ

## 検討すること
- vue or rails only
- vue使う場合，api作成するのでSwagger導入すること

**Comment by takaaa220** [comment]
#44 
掲示板機能はレオさんがやってくれそうなので，こちらのIssueはCloseしやす
