### ISSUE TITLE
[メッセージ機能] マッチング後のDM

### ISSUE THREAD

**Issue by takaaa220** [WEBsinjyuku/github-open-products#48]

**Comment by takaaa220** [comment]
## マッチング後の参加者と主催者のDM機能
### 概要
- マッチングした人たちのみのClosedなDM
- 双方向通信を行う
- もうLineやTwitterのDMを想像してもらえれば

### DB
要検討

### 画面イメージ
TODO

**Comment by takaaa220** [comment]
- [ ] sidekiq and redis の設定 (dockerなど) -> とりあえずlocal環境
- [ ] model の作成，validation の設定
- [ ]

**Comment by tsu-nera** [comment]
## レビュー指摘 tsu-nera

- is_groupの is_の命名に違和感は感じましたが、ネットで調べるとそういう命名規約の慣例もあるようなので、大丈夫です。

- user_group (中間テーブル) -> user_room の誤記ですか？

- グループDMというのがイメージつかなくて。グループLINEのようなものですか？もう少し資料を継ぎ足す予定あります？なければ簡単に説明を追記してもらってもいいでしょうか？

**Comment by takaaa220** [comment]
> user_group (中間テーブル) -> user_room の誤記ですか？

誤記です
修正します．

> グループDMというのがイメージつかなくて。グループLINEのようなものですか？もう少し資料を継ぎ足す予定あります？なければ簡単に説明を追記してもらってもいいでしょうか？

そうですね．
そこまでやるかわからないですけど，グループチャット機能を使えるようにするとしたらって話です．
とりあえず1:1を想定しているので，is_groupカラムは最初の段階ではつけない予定です．

**Comment by tsu-nera** [comment]
よく設計できていて、たいへんもうしわけないけれども、いったん保留にさせてください。
