### ISSUE TITLE
2019/01/21: 打ち合わせ(オンライン) 22:00 ~ 25:00

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/github-open-products#53]
## 検討内容

- [x] DB設計

**Comment by tsu-nera** [comment]
## オンライン会議のまとめ

* GitHubリポジトリの詳細情報(スター数、参加者数)をテーブルに保持するのは避けたい。 （サービスとGitHubで参加者数などの表示内容が異なるケースが発生させたくない） そのため、GitHubの情報はAPIで取得し、サービスで利用するテーブルのデータとは重複させない。
* GitHubAPIの利用にあたり、データ検索のタイミングを決める必要がある。 Railsのキャッシュが切れたら、DBアクセスをしたらどうか？
* 1次リリースはマッチング機能より掲示板機能がメイン。
* 中間テーブルは作成しない。 
* カラムは各自が実装する中で増やす。

**Comment by takahashi19** [comment]
ありがとうございます！
DB検討→userとpostの中間テーブルは、Connpassの様に参加者同士が参加者を見られるというメリットも大きいのですね。「中の雰囲気を見てみたい」「どんな人が参加してるか知りたい」というのは、募集系のサイトではユーザーにとってニーズはあるかなと。フェーズは分けても後々実装は必要と考えます。あとで追加はできるので次週以降の課題だと思います。

**Comment by tsu-nera** [comment]
閉じる。
