### ISSUE TITLE
アカウント削除機能の検討

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#57]
CRUDを整理して思ったのですが、ユーザ退会（アカウント削除）の機能は想定していましたっけ？

わたしは、この記事を読んで同感していて、退会機能不要論者になりました。
https://qiita.com/ponkotuy/items/6049388d564fb4385f4e

**Comment by takaaa220** [comment]
個人的にはアカウント情報を消すのは、なしですね

**Comment by tsu-nera** [comment]
とりあえずなしで。
