### ISSUE TITLE
[参加機能] 中間テーブル置いて参加機能を追加

### ISSUE THREAD

**Issue by takaaa220** [WEBsinjyuku/github-open-products#59]
## 概要
そもそもマッチングがないとDMいらないので
バックエンドのみ作成
フロントは僕の担当ではない

## DB

user_projects

| カラム | 型 | null | default | 外部制約 |
| :-----: | :-: | :--: | :------: | :-------: |
| id | integer | false | (increment) | false |
| user_id | integer | false | null | true |
| post_id | integer | false | null | true |

userとpostを多対多の関係にする

**Comment by tsu-nera** [comment]
参加機能はいったん保留にします。
