### ISSUE TITLE
[アーキテクチャ] GitHubからの情報をいつ、どう取得するか

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#65]
GitHubからの情報をいつ取得するかが気になります。
Keywords, Stars、Contributer、descriptionが変動するため、これは表示のたびに取得する必要があると思います。

はじめ、Rails Cacheをつかってキャッシュで情報をもって、APIを表示するたびに叩けばいいと思ったのですが、
ソートや検索機能を考えるとDBに情報がないとそれが実現できないことに気づきました。

ほかのサービスとか、このへんどう解決しているのですかね？？

今すぐよい代替案も思いつかなくて、とりあえず問題提起だけしておきます。

**Comment by tsu-nera** [comment]
1. 
index, show,  create, editのたびに GitHub APIを叩く。取得した情報はDBに保存。

2. 
createt、editのたびに GitHub APIを叩く。取得した情報はDBに保存。
index、showのたびに GitHub APIは叩かない。DBの情報をReadする。

深夜3時頃、DBの情報を更新するタスクをスケジューリングして、一日一回更新する。

3.
createt、editのたびに GitHub APIを叩く。取得した情報はDBに保存。
index、showのたびに GitHub APIは叩かない。DBの情報をReadする。

キャッシュが存在するとき、キャッシュを参照する。
キャッシュが存在しないとき、GitHub APIを叩く。取得した情報はDBとキャッシュに保存。

キャッシュは例えば１時間を期限にする。

**Comment by tsu-nera** [comment]
DBにいれない方針はいいですね。
スモールスタートの方針なので、必要に応じて機能を拡張していけばいいですね。

他の人もよさそうなら、保存はしない方針でもわたしも賛成です。

**Comment by dh-megane** [comment]
@tsu-nera @takaaa220 
助言ありがとうございました。

**DB利用**
自分もDBにデータを保持しない案で大丈夫です。
絞込機能・ソート機能を機能拡張する際は、Vue.jsであればDBにデータを保持せずとも
実現できるのではないかと思っています。
https://tmykndr.hatenablog.com/entry/2018/09/09/002351

なので、Vueでの実装、頑張ります。

**キャッシュ**
キャッシュを利用せず、毎回データ取得を行ってもよいのではと思ってます。
けっこうダサい？、遅いですかね？

**Comment by takaaa220** [comment]
> DB利用
自分もDBにデータを保持しない案で大丈夫です。
絞込機能・ソート機能を機能拡張する際は、Vue.jsであればDBにデータを保持せずとも
実現できるのではないかと思っています。
https://tmykndr.hatenablog.com/entry/2018/09/09/002351
>
> なので、Vueでの実装、頑張ります。

スケールした時にアプリケーション側でのソートは死にそうです。

> キャッシュ
キャッシュを利用せず、毎回データ取得を行ってもよいのではと思ってます。
けっこうダサい？、遅いですかね？

さすがに厳しいかと〜

ふと思ったんですが、やはりDBに入れない案はちょっと厳しいような気がしてきました。

理由: 100件の登録があるとすると、100回アクセスする必要があるので。(かなり遅そう)

**Comment by dh-megane** [comment]
> 100件の登録があると100アクセス〜
なるほどです。

**Comment by tsu-nera** [comment]
キャッシュするか、https://github.com/WEBsinjyuku/github-open-products/issues/65#issuecomment-456695987　の案だと思います。

**Comment by takaaa220** [comment]
そうですね
最初のリリースは叩く方向でいいかと

できれば，APIを叩くときは並列で処理したいですね．

**Comment by tsu-nera** [comment]
## まとめ

- 情報取得は、各ページでgithub apiを叩いて取得。
- 第一リリースでは、DB やキャッシュ などは使わず。
- 第一リリース以後に、改善としてDB保存を検討する。

**Comment by tsu-nera** [comment]
↑のを #56 で相談して、合意が取れれば closeする。

**Comment by takaaa220** [comment]
あら，キャッシュすら使わない結論になったんですね
了解です〜

**Comment by tsu-nera** [comment]
キャッシュは、日曜の打ち合わせで議題に上げたときに話しましょうか。

**Comment by tsu-nera** [comment]
## まとめ

- とりあえず第一リリースはAPIを叩く。DBには情報持たない。
- Cacheは機能追加する
- 並列処理をする
