### ISSUE TITLE
メール機能（とチャット機能の棲み分けの検討）

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/github-open-products#90]
個別表示機能にメール機能をつける？そうすると、チャット機能との棲み分けはどうする？
チャット機能、重い機能なので、どうするどうする？

**Comment by takaaa220** [comment]
メールはあくまでも通知の一環として，持ってるってのが僕のイメージなんですよね

最初の段階は，openな掲示板機能があって，参加機能をおすとこのユーザが参加を希望しています．
って感じでメールアドレスを置きつつ，あとは起案者にProjectへの招待をさせることのみのためにメール機能が存在すると思っています．

なので，そこはあくまで別件かと思ってます．

**Comment by tsu-nera** [comment]
openな掲示板機能と、今平田さんが着手していたチャットはどうつながりますか？チャットは確かclosedなルームでしたよね？？

**Comment by tsu-nera** [comment]
openな掲示板、メール、チャットの３人が登場します？？

**Comment by tsu-nera** [comment]
私のイメージは、メールはチャットが完成する間のつなぎのイメージで、openな掲示板はないとは思っていました。ただ、平田さんの指摘をよんで、必要と認識を改めました。

**Comment by takaaa220** [comment]
えー原田さんの意見を聞いて確かにって思ってきました．

単純に誰でもできるDMって形の方がいいですかね
そんな気がしてきました．

**Comment by takaaa220** [comment]
ちょっと考えますが，当分の間は完成しないので保留とさせてください

**Comment by tsu-nera** [comment]
これ、ちょっと悩む議題なので、時間があるときに日曜の打ち合わせの時とかに話すのでもいいです。

**Comment by tsu-nera** [comment]
リリース計画のときに一緒に議論する。

**Comment by tsu-nera** [comment]
チャットは平田さんがいなくなり、いったん白紙ベースで考え直すことにする。
